#!/bin/bash

#travelsafe
echo 'travel restrictions'
pipenv run python cli.py travelsafe restrictions \
    --origin ES \
    --destination FR \
    --origin-type country_code \
    --destination-type country_code \
    --date 2021-09-10 \
    > /tmp/restrictions

echo 'local summary'
 pipenv run python cli.py travelsafe local-summary \
    --location ES \
    --location-type country_code \
   > /tmp/summary

echo 'airline meansures'
 pipenv run python cli.py travelsafe airline-measures \
    --code LH \
   > /tmp/summary

#invoices
echo 'all invoices'
pipenv run python cli.py expenses invoices all > /tmp/all_invoices
echo 'invoice'
pipenv run python cli.py expenses invoices get --id some_test_invoice_id > /tmp/invoice
echo 'invoice lines'
pipenv run python cli.py expenses invoices lines > /tmp/invoice_lines

#invoice profiles
echo 'invoice profiles'
pipenv run python cli.py expenses invoice-profiles all > /tmp/invoice_profiles

#cost centers
echo 'all cost centers'
pipenv run python cli.py cost-centers all > /tmp/cost_centers
echo 'cost center'
pipenv run python cli.py cost-centers get --id 85027 > /tmp/cost_center

#scim users
echo 'all scim'
pipenv run python cli.py scim users all > /tmp/all_scim
echo 'user'
pipenv run python cli.py scim users get --id some_user_id > /tmp/scim_user

#discovery
echo 'schemas'
pipenv run python cli.py scim discovery schemas > /tmp/schemas
echo 'user schema'
pipenv run python cli.py scim discovery user-schema > /tmp/user_schemas
echo 'enterprise schema'
pipenv run python cli.py scim discovery enterprise-schema > /tmp/enteprise_schemas
echo 'resource types'
pipenv run python cli.py scim discovery resource-types > /tmp/resource_types

#webhooks
echo 'all webhooks'
pipenv run python cli.py webhooks all > /tmp/all_webhooks
echo 'webhook'
pipenv run python cli.py webhooks get --id b4ab65a2-31b6-4cf8-9cfb-f0788c47f7c7 > /tmp/webhook
echo 'test webhook'
pipenv run python cli.py webhooks test --id b4ab65a2-31b6-4cf8-9cfb-f0788c47f7c7 > /tmp/test_webhook

#trips
echo 'all trips'
pipenv run python cli.py trips all > /tmp/all_trips
echo 'all bookings'
pipenv run python cli.py trips bookings > /tmp/all_bookings

#users
echo 'all users'
pipenv run python cli.py users all > /tmp/all_users

#greenperk
echo 'flight emissions'
pipenv run python cli.py greenperk flight-emissions \
    --origin BCN \
    --destination LHR \
    --cabin_class economy \
    --airline_code BA \
  > /tmp/flight_emissions

echo 'train emissions'
pipenv run python cli.py greenperk train-emissions \
    --origin_id c44ba069-4109-4b40-815c-bf519c2c2844 \
    --destination_id 637d125e-9d00-478a-822c-e60c6e219227 \
    --vendor eurostar \
  > /tmp/train_emissions

echo 'car emissions'
pipenv run python cli.py greenperk car-emissions \
    --acriss_code MCFD \
    --num_days 2 \
    --distance_per_day 100 \
  > /tmp/car_emissions

echo 'hotel emissions'
pipenv run python cli.py greenperk hotel-emissions \
    --country_code ES \
    --num_nights 2 \
  > /tmp/hotel_emissions
